import type { Metadata } from "next";
import "./globals.css";
import { Oxanium, Roboto } from "next/font/google";
import { cn } from "@/lib/utils";

const robotoHeading = Roboto({subsets:['latin'],variable:'--font-heading'});

const oxanium = Oxanium({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", oxanium.variable, robotoHeading.variable)}
    >
      <body className="min-h-full flex flex-col ml-10">
        {children}
      </body>
    </html>
  );
}
